name: Update Disaster Map

on:
  schedule:
    - cron: "0 * * * *"  # every hour on the hour
  workflow_dispatch:     # manual run button
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas folium requests geopandas

      - name: Run data fetchers
        run: |
          python fetch_noaa.py
          python fetch_usgs.py
          python fetch_wildfire.py
          python merge_feeds.py
          python make_map.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update disaster map"
          git push